### ISSUE TITLE
Mapped videos shown when clicking on "Show unmapped videos"

### ISSUE THREAD

**Issue by Plushb9rry** [frog23/TomScottMap#49]
Hey @frog23, I think the recent push brought a bug with it /s. 

- In  [review.html](https://www.frog23.net/TomScottMap/review.html) , The button "SHOW UNMAPPED VIDEOS ONLY" or "SHOW ALL VIDEOS" Is not showing desired results. It just triggers the bottom right map panel. 

![image](https://user-images.githubusercontent.com/77117781/178144522-c1aa2221-988c-46da-b4a2-7f63a3c80213.png)

![image](https://user-images.githubusercontent.com/77117781/178144537-3caa7343-4825-4db7-b43b-d303fb9bb874.png)

**Comment by frog23** [comment]
Thanks for spotting this. Apparently this issue was already introduced in 93d696b7d2b5d1464410f3364cb944e3786549dd but somehow I forgot to push the file to the server after the commit. I only had it in my little test environment. Only with the update earlier did I replace the file. Anyways, it was only a small issue and is now fixed.
