### ISSUE TITLE
New video not added?

### ISSUE THREAD

**Issue by Plushb9rry** [frog23/TomScottMap#61]
as I write this the video is uploaded on the main channel, 8 mins ago. That doesn't seem to be a delay, maybe the script has stopped?
![image](https://user-images.githubusercontent.com/77117781/188478876-d9c4acf3-25a7-4ede-8a5d-9fb71afe2c25.png)

**Comment by frog23** [comment]
The auto update script tries to load the RSS feed (yes, those are still a thing) of the channel to check for new videos, every 5 minutes after 16:00 GMT/BST for an hour. For some reason today it took longer for the feeds to update, even though the video was already published, maybe because the CDN was slower today. Anyways it was automatically updated 20 minutes ago.
